stackabletech/commons-operator

rust/crd/src/tls.rs

*Please add a description here. This will become the commit message of the merge request later.*
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

fix: Make Tls verification attribute public

---

rust/operator-binary/src/main.rs

*Please add a description here. This will become the commit message of the merge request later.*
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)

Fix startup message not beeing shown

---

Cargo.lock
Cargo.toml
rust/operator-binary/Cargo.toml

*Please add a description here. This will become the commit message of the merge request later.*
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Switch to workspace dependencies

---

Cargo.lock
Cargo.toml
deploy/helm/commons-operator/crds/crds.yaml
rust/operator-binary/src/main.rs

Replaces https://github.com/stackabletech/commons-operator/pull/180
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update to operator-rs 0.58.0

---

Cargo.lock
Cargo.toml
deploy/helm/commons-operator/crds/crds.yaml

Better CRD docs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat: Better CRD docs

---

docs/modules/commons-operator/pages/configuration.adoc
docs/modules/commons-operator/pages/reference/crds.adoc
docs/modules/commons-operator/pages/reference/index.adoc
docs/modules/commons-operator/partials/nav.adoc

see title
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat(docs): reference docs

---

docs/modules/commons-operator/pages/index.adoc
tests/templates/kuttl/restarter/00-rbac.yaml.j2
tests/templates/kuttl/restarter/10-assert.yaml
tests/templates/kuttl/restarter/10-sleep.yaml
tests/templates/kuttl/restarter/20-assert.yaml
tests/templates/kuttl/restarter/20-update-cm.yaml
tests/test-definition.yaml

Fixes #196 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat(tests): added test for restarter

---

CHANGELOG.md
deploy/helm/commons-operator/templates/_helpers.tpl
deploy/helm/commons-operator/templates/deployment.yaml
deploy/helm/commons-operator/templates/roles.yaml
deploy/helm/commons-operator/values.yaml

Part of: https://github.com/stackabletech/issues/issues/501

feat(helm): support labels in values.yaml

---

rust/operator-binary/src/restart_controller/pod.rs

This shouldn't change any functionality, just add some logging statements in order to better be able to debug restarting of pods due to certificate lifetimes, should it ever become necessary.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Adds logging to restart logic for expired certificates.

---

tests/release.yaml
tests/templates/kuttl/restarter/00-patch-ns.yaml.j2

Part of stackabletech/issues#566.
OKD:
```
--- PASS: kuttl (53.80s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/restarter_openshift-true (46.05s)
```
Azure:
```
--- PASS: kuttl (41.59s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/restarter_openshift-false (39.55s)
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

tests: added namespace patch for openshift tests

---

Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deny.toml

Upgrade dependencies
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Upgrade dependencies

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/commons-operator/crds/crds.yaml
rust/operator-binary/src/restart_controller/statefulset.rs

Part of https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Update to operator-rs 0.76.0 and use new S3 structs

---

CHANGELOG.md

fix: corrected changelog as entry was entered in the wrong section.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

fix: corrected changelog

---

docs/modules/commons-operator/pages/pod-enrichment.adoc
rust/operator-binary/src/pod_enrichment_controller.rs

See #292
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

Add deprecation warning for pod enricher

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/commons-operator/Chart.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1-rc2

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json

PR to fix unmaintained crate cargo deny errors
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: bump stackable-operator version and cargo update

---

.github/workflows/build.yml
CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/commons-operator/Chart.yaml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

release: 24.11.1

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/commons-operator/templates/roles.yaml
rust/operator-binary/src/pod_enrichment_controller.rs
rust/operator-binary/src/restart_controller/pod.rs
rust/operator-binary/src/restart_controller/statefulset.rs

Part of https://github.com/stackabletech/operator-rs/issues/942
```[tasklist]
```

chore: Update to operator-rs 0.84.0

---

CHANGELOG.md

*Please add a description here. This will become the commit message of the merge request later.*
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

chore: Updated changelog to add missing entry after bump to op-rs

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
rust/operator-binary/Cargo.toml
rust/operator-binary/src/main.rs

**Use `Tracing::pre_configured` from stackable-telemetry**
Breaking changes:
- The console log level was set by `COMMONS_OPERATOR_LOG`, and is now set by `CONSOLE_LOG`.
- The file log level was set by `COMMONS_OPERATOR_LOG`, and is now set by `FILE_LOG`.
- The file log directory was previously changed to `ROLLING_LOGS`, but has been updated to `ROLLING_LOGS_DIR`.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

feat!: Use `Tracing::pre_configured` from stackable-telemetry

---

docs/modules/commons-operator/pages/installation.adoc

Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```

docs: Update helm install commands

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
deploy/helm/commons-operator/Chart.yaml
deploy/helm/commons-operator/crds/crds.yaml
docs/antora.yml
tests/release.yaml

> [!CAUTION]
> ## DO NOT MERGE MANUALLY!
> This branch will be merged (and the commit tagged) by stackable-utils once any necessary commits have been cherry-picked to here from the main branch.

chore: Release 25.7.0-rc1

---

CHANGELOG.md
Cargo.lock
Cargo.nix
Cargo.toml
crate-hashes.json
deploy/helm/commons-operator/crds/crds.yaml
rust/operator-binary/src/main.rs

Part of https://github.com/stackabletech/issues/issues/733. This adds the EoS checker to the operator.

feat: Add EoS checker
